#!/bin/bash

echo ......................................
echo ......................................
echo ......................................
echo iniciando o script com docker init....
echo ......................................
echo ......................................
echo ......................................

sudo docker swarm init --advertise-addr=192.168.18.110

echo ......................................
echo ......................................
echo ......................................
echo Exportando o token do node master para arquivo token.txt...
echo ......................................
echo ......................................
echo ......................................



sudo docker swarm join-token -q worker > /vagrant/token.txt
